# Generated by Django 2.0.3 on 2018-07-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hictracks', '0002_auto_20180715_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetophenotype',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hictracks.Gene'),
        ),
        migrations.AlterField(
            model_name='phenotype',
            name='genes',
            field=models.ManyToManyField(related_name='phenotypes', through='hictracks.GeneToPhenotype', to='hictracks.Gene'),
        ),
    ]
