# Generated by Django 2.0.3 on 2018-07-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hictracks', '0003_auto_20180715_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='biotype',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='ensembl_gene_id',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='gene_symbol',
        ),
        migrations.AddField(
            model_name='bedfileentry',
            name='biotype',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedfileentry',
            name='ensembl_gene_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
